---
trigger:
  batch: true
  branches:
    include:
      - main

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/master
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts (1)'

parameters:
  - name: overrideAction
    type: string
    default: plan
    values:
      - plan
      - apply
      - destroy

  - name: environment_components
    type: object
    default:
      - deployment: sbox_dynatrace_availability_dashboards
        environment: sbox
        component: dt-availability-dashboards
        service_connection: dts-sharedservices-sbox
        dependsOn: Precheck
        keyvault:
          service_connection: DCD-CFT-Sandbox
          name: infra-vault-nonprod
          secret_name: dynatrace-platops-api-key

      - deployment: demo_dynatrace_availability_dashboards
        environment: demo
        component: dt-availability-dashboards
        service_connection: dts-sharedservices-demo
        dependsOn: Precheck
        keyvault:
          service_connection: DCD-CFT-Sandbox
          name: infra-vault-nonprod
          secret_name: dynatrace-platops-api-key

      - deployment: ithc_dynatrace_availability_dashboards
        environment: ithc
        component: dt-availability-dashboards
        service_connection: dts-sharedservices-ithc
        dependsOn: Precheck
        keyvault:
          service_connection: DCD-CFT-Sandbox
          name: infra-vault-nonprod
          secret_name: dynatrace-platops-api-key

      - deployment: ptlsbox_dynatrace_availability_dashboards
        environment: ptlsbox
        component: dt-availability-dashboards
        service_connection: dts-sharedservicesptl-sbox
        dependsOn: Precheck
        keyvault:
          service_connection: DCD-CFT-Sandbox
          name: infra-vault-nonprod
          secret_name: dynatrace-platops-api-key

      - deployment: aat_dynatrace_availability_dashboards
        environment: stg
        component: dt-availability-dashboards
        service_connection: dts-sharedservices-stg
        dependsOn: Precheck
        keyvault:
          service_connection: DCD-CFT-Sandbox
          name: infra-vault-nonprod
          secret_name: dynatrace-platops-api-key

      - deployment: perftest_dynatrace_availability_dashboards
        environment: test
        component: dt-availability-dashboards
        service_connection: dts-sharedservices-test
        dependsOn: Precheck
        keyvault:
          service_connection: DCD-CFT-Sandbox
          name: infra-vault-nonprod
          secret_name: dynatrace-platops-api-key

variables:
  - name: globalTfCommandOptions
    value: -parallelism=1
  - name: timeoutInMinutes
    value: 60
  - name: agentPool
    value: ubuntu-latest
  - name: build
    value: $(Build.BuildNumber)
  - name: product
    value: dt-availability-dashboards
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        displayName: Precheck
        pool:
          vmImage: ${{ variables.agentPool }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-token'
              serviceConnection: 'DCD-CFT-Sandbox'
              overrideAction: ${{ parameters.overrideAction }}

  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - job: TerraformPlanApply
            displayName: ${{ deployment.environment }} - terraform ${{ parameters.overrideAction }}
            pool:
              vmImage: ${{ variables.agentPool }}
            timeoutInMinutes: ${{ variables.timeoutInMinutes }}
            steps:
              - task: AzureKeyVault@2
                displayName: 'Pre-job: Retrieve keyvault secret for Dynatrace API Key'
                inputs:
                  azureSubscription: ${{ deployment.keyvault.service_connection }}
                  KeyVaultName: ${{ deployment.keyvault.name }}
                  SecretsFilter: ${{ deployment.keyvault.secret_name }}
                  RunAsPreJob: true
              - template: steps/terraform.yaml@cnp-azuredevops-libraries
                parameters:
                  overrideAction: ${{ parameters.overrideAction }}
                  environment: ${{ deployment.environment }}
                  component: ${{ deployment.component }}
                  serviceConnection: ${{ deployment.service_connection }}
                  terraformInitSubscription: ${{ variables.terraformInitSubscription }}
                  product: ${{ variables.product }}
                  terraformEnvironmentVariables:
                    TF_VAR_dynatrace_platops_api_key: $(dynatrace-platops-api-key)
                  planCommandOptions: ${{ variables.globalTfCommandOptions }}
                  applyCommandOptions: ${{ variables.globalTfCommandOptions }}
                  destroyCommandOptions: ${{ variables.globalTfCommandOptions }}
