---
trigger: none

stages:
  - stage: test
    jobs:
      - job:
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'DCD-CFTAPPS-SBOX'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            failOnStandardError: true
            inlineScript: |
              az account set --subscription b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb
              az aks get-credentials --resource-group cft-sbox-00-rg --name cft-sbox-00-aks
              


