---
name: Auto-approve automated nonprod pull requests
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    if: ${{ (contains(github.event.pull_request.labels.*.name, 'auto-approve')) && github.actor == 'hmcts-platform-operations'}}
    runs-on: ubuntu-latest
    steps:
      - run: gh pr review --repo ${{ github.repository }} $PR_NUMBER --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
