---
name: Auto-approve automated nonprod pull requests
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    # if: ${{ github.event.label.name == 'auto-approve' && github.actor == 'hmcts-platform-operations'}}
    runs-on: ubuntu-latest
    steps:
      - run: echo $PR_NUMBER
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }
