---
name: Auto-approve automated nonprod pull requests
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to auto-approve'
        required: true
        type: string
      environment:
        description: 'Non-prod environment key'
        required: true
        type: choice
        options:
          - sbox
          - demo
          - ptlsbox
          - stg
          - test
          - ithc

jobs:
  build:
    if: ${{ (contains(github.event.pull_request.labels.*.name, 'auto-approve')) && github.triggering_actor == 'hmcts-platform-operations'}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.environment }}
          gh pr review --repo ${{ github.repository }} ${{ github.event.inputs.pr_number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
