---
name: Run all pre-commit hooks

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'
      - run: go install github.com/terraform-docs/terraform-docs@v0.16.0
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.2
        if: always()
