---
name: Sanity checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pre-reqs
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
      - name: Lint Tests
        run: ./tests/lint-yaml.sh
